-- ══════════════════════════════════════════════════════════════════════════
-- Migration 047: Create procurement_submissions table
-- Purpose: Stores vendor quotation submissions from the Procurement Portal.
--          When a submission is approved, its line_items are fanned out into
--          procurement_expenses (existing table) for inventory/analytics.
-- Run in: Supabase SQL Editor
-- ══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS procurement_submissions (
    id                  UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),

    -- Reference & identity
    ref                 TEXT        UNIQUE NOT NULL,          -- e.g. PCQ-ABC123 (generated by portal)
    title               TEXT        NOT NULL,
    status              TEXT        NOT NULL DEFAULT 'pending'
                                    CHECK (status IN ('pending','approved','rejected','paid')),

    -- Project linkage (one of these will be set, depending on whether
    -- the project is a live property or a draft estate)
    property_id         UUID        REFERENCES properties(id) ON DELETE SET NULL,
    estate_draft_id     UUID        REFERENCES estate_drafts(id) ON DELETE SET NULL,

    -- Vendor identity snapshot (copy at submission time so history
    -- is preserved even if the vendor record changes later)
    vendor_id           UUID        REFERENCES vendors(id) ON DELETE SET NULL,
    vendor_name         TEXT        NOT NULL,
    contact_name        TEXT,
    phone               TEXT,
    email               TEXT,
    rc_number           TEXT,
    tin                 TEXT,

    -- Bank account (snapshot)
    bank_name           TEXT,
    account_number      TEXT,
    account_name        TEXT,

    -- Financials
    total_amount        DECIMAL(15,2) NOT NULL DEFAULT 0,
    notes               TEXT,

    -- Line items stored as JSONB array.
    -- Each element: { description, category, qty, unit, unitPrice, amount }
    line_items          JSONB       NOT NULL DEFAULT '[]',

    -- Workflow timestamps & actors
    submitted_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reviewed_at         TIMESTAMPTZ,
    reviewed_by         UUID        REFERENCES admins(id) ON DELETE SET NULL,

    -- Outcome
    rejection_reason    TEXT,
    pay_reference       TEXT,

    -- Audit
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Indexes ───────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_proc_sub_status
    ON procurement_submissions(status);

CREATE INDEX IF NOT EXISTS idx_proc_sub_vendor
    ON procurement_submissions(vendor_id);

CREATE INDEX IF NOT EXISTS idx_proc_sub_property
    ON procurement_submissions(property_id);

CREATE INDEX IF NOT EXISTS idx_proc_sub_draft
    ON procurement_submissions(estate_draft_id);

CREATE INDEX IF NOT EXISTS idx_proc_sub_submitted_at
    ON procurement_submissions(submitted_at DESC);

-- ── Auto-update updated_at ─────────────────────────────────────────────
-- Reuse or create a generic trigger function if it doesn't exist yet
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_proc_sub_updated_at
    BEFORE UPDATE ON procurement_submissions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ── Row-Level Security (optional but recommended for Supabase) ────────────
-- Allow service_role (your FastAPI backend) full access.
-- Adjust anon/authenticated policies to your auth model.
ALTER TABLE procurement_submissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_all" ON procurement_submissions
    FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ── Notify PostgREST to reload schema ─────────────────────────────────────
NOTIFY pgrst, 'reload schema';